glamira_bigquery_profile:
  target: "{{ env_var('DBT_TARGET', 'dev') }}" # Mặc định là 'dev' nếu không truyền biến
  outputs:
    # 1. Môi trường phát triển trên máy cá nhân của bạn
    dev_oauth:
      type: bigquery
      method: oauth             # Sử dụng tài khoản cá nhân đã đăng nhập qua gcloud
      project: glamira-dec-k23-huy
      dataset: glamira_transform_dev # Dataset riêng của bạn để test code
      threads: 4
      location: US

    # 2. Môi trường chạy tự động trên Cloud sau này
    dev:
      type: bigquery
      method: service-account
      project: glamira-dec-k23-huy
      dataset: glamira # Dataset chính thức cho báo cáo
      threads: 4
      # Điền trực tiếp nội dung chuỗi JSON lấy từ biến môi trường của hệ thống CI/CD
      keyfile: "{{ env_var('GCP_SA_KEY_JSON') }}"
      location: US